alias: Battery EMS Control Based on EMHASS Forecasts
description: ""
triggers:
  - minutes: /5
    trigger: time_pattern
actions:
  - variables:
      p_load_timestamp: >
        {%- set ns = namespace(value='unknown') %} {%- for item in
        state_attr('sensor.mpc_p_load_forecast', 'forecasts') %}
          {%- if as_datetime(item.date) <= utcnow() %}
            {% set ns.value = utcnow() | string + item.date | string %}
          {%- endif %}
        {%- endfor %} {{ ns.value }}
      p_batt: >
        {%- set ns = namespace(value=states('sensor.mpc_p_batt_forecast')) %}
        {%- for item in state_attr('sensor.mpc_p_batt_forecast',
        'battery_scheduled_power') %}
          {%- if as_datetime(item.date) <= utcnow() %}
            {% set ns.value = item.mpc_p_batt_forecast %}
          {%- endif %}
        {%- endfor %} {{ ns.value | float('unknown') }}
      p_grid: >
        {%- set ns = namespace(value=states('sensor.mpc_p_grid_forecast')) %}
        {%- for item in state_attr('sensor.mpc_p_grid_forecast', 'forecasts') %}
          {%- if as_datetime(item.date) <= utcnow() %}
            {% set ns.value = item.mpc_p_grid_forecast %}
          {%- endif %}
        {%- endfor %} {{ ns.value | float('unknown') }}
      p_load: >
        {%- set ns = namespace(value=states('sensor.mpc_p_load_forecast')) %}
        {%- for item in state_attr('sensor.mpc_p_load_forecast', 'forecasts') %}
          {%- if as_datetime(item.date) <= utcnow() %}
            {% set ns.value = item.mpc_p_load_forecast %}
          {%- endif %}
        {%- endfor %} {{ ns.value | float('unknown') }}
      p_pv: >
        {%- set ns = namespace(value=states('sensor.mpc_p_pv_forecast')) %} {%-
        for item in state_attr('sensor.mpc_p_pv_forecast', 'forecasts') %}
          {%- if as_datetime(item.date) <= utcnow() %}
            {% set ns.value = item.mpc_p_pv_forecast %}
          {%- endif %}
        {%- endfor %} {{ ns.value | float('unknown') }}
      p_hybrid_inverter: >
        {%- set ns = namespace(value=states('sensor.mpc_p_hybrid_inverter')) %}
        {%- for item in state_attr('sensor.mpc_p_hybrid_inverter', 'forecasts')
        %}
          {%- if as_datetime(item.date) <= utcnow() %}
            {% set ns.value = item.mpc_p_hybrid_inverter %}
          {%- endif %}
        {%- endfor %} {{ ns.value | float('unknown') }}
      p_pv_curtailment: >
        {%- set ns = namespace(value=states('sensor.mpc_p_pv_curtailment')) %}
        {%- for item in state_attr('sensor.mpc_p_pv_curtailment', 'forecasts')
        %}
          {%- if as_datetime(item.date) <= utcnow() %}
            {% set ns.value = item.mpc_p_pv_curtailment %}
          {%- endif %}
        {%- endfor %} {{ ns.value | float('unknown') }}
      soc: >
        {{ states('sensor.sigen_plant_battery_state_of_charge') |
        float('unknown') }}
      soc_full_threshold: 99.9
      planned_pv_curtailment_kwh: >
        {#- next 10 hours #} {{ state_attr('sensor.mpc_p_pv_curtailment',
        'forecasts')[:120]|map(attribute='mpc_p_pv_curtailment')|map('float')|sum
        / 12000 }}
      max_grid_import: 12949
      max_grid_export: -9999
      max_inverter_discharge: 9989
      max_inverter_charge: -9989
      max_grid_export_kw: 10
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ states('sensor.sigen_plant_grid_connection_status') != 'On
              Grid' }}
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: DEFAULT (Backup Power) Self-consume from battery
            action: input_text.set_value
          - data:
              control_mode: Maximum Self Consumption
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: >-
              {{ (p_grid >= max_grid_import or p_hybrid_inverter <=
              max_inverter_charge) and p_pv_curtailment > 0 and p_pv ==
              p_pv_curtailment }}
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: Full PV curtailment and grid charge at full rate
            action: input_text.set_value
          - data:
              control_mode: Command Charging (PV First)
              pv_max_power_limit_kw: 0.05
              export_limit_kw: 0
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: >-
              {{ soc >= 100.0 and p_grid > 0 and p_batt <= 0 and
              p_pv_curtailment > 0 and p_pv == p_pv_curtailment }}
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: Battery full, full PV curtailment, grid powers home
            action: input_text.set_value
          - data:
              control_mode: Maximum Self Consumption
              pv_max_power_limit_kw: 0.05
              export_limit_kw: 0
              discharge_limit_kw: 0
              pcs_export_limit_kw: 0
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: >-
              {{ p_grid > 0 and p_batt < 0 and p_pv_curtailment > 0 and p_pv ==
              p_pv_curtailment }}
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: Full PV curtailment and grid charge at partial rate
            action: input_text.set_value
          - data:
              control_mode: Command Charging (PV First)
              pv_max_power_limit_kw: 0.05
              export_limit_kw: 0
              charge_limit_kw: "{{ (-p_batt / 1000) | round(3) }}"
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: >-
              {{ p_grid == p_load and p_batt == 0 and p_pv_curtailment > 0 and
              p_pv == p_pv_curtailment }}
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: Full PV curtailment, grid powers home
            action: input_text.set_value
          - data:
              control_mode: Maximum Self Consumption
              pv_max_power_limit_kw: 0.05
              export_limit_kw: 0
              charge_limit_kw: 0
              discharge_limit_kw: 0
              pcs_export_limit_kw: 0
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: >-
              {{ (states('sensor.amber_effective_general_price') | float) < 0
              and planned_pv_curtailment_kwh > 0 and (p_grid >= max_grid_import
              or p_hybrid_inverter <= max_inverter_charge) }}
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: >-
                Proactive full PV curtailment and grid charge at full rate
                (negative buy)
            action: input_text.set_value
          - data:
              control_mode: Command Charging (PV First)
              export_limit_kw: 0
              pv_max_power_limit_kw: 0.05
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: >-
              {{ p_grid >= max_grid_import or p_hybrid_inverter <=
              max_inverter_charge }}
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: Grid charge at full rate
            action: input_text.set_value
          - data:
              control_mode: Command Charging (PV First)
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: >-
              {{ p_hybrid_inverter == 0 and p_load == p_grid and p_pv == -p_batt
              and p_batt < 0 }}
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: DC-coupled PV charging, grid powers home
            action: input_text.set_value
          - data:
              control_mode: Maximum Self Consumption
              pcs_export_limit_kw: 0
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: >-
              {{ p_grid > 0 and p_batt < 0 and p_hybrid_inverter < 0 and p_pv >
              0 }}
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: Grid charge at partial rate (day)
            action: input_text.set_value
          - data:
              control_mode: Command Charging (PV First)
              pcs_import_limit_kw: "{{ (-p_hybrid_inverter / 1000) | round(3) }}"
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: "{{ p_grid > 0 and p_batt < 0 }}"
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: Grid charge at partial rate (night)
            action: input_text.set_value
          - data:
              control_mode: Command Charging (PV First)
              charge_limit_kw: "{{ (-p_batt / 1000) | round(3) }}"
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: >-
              {{ soc >= soc_full_threshold and p_pv_curtailment > 0 and p_grid
              == 0 and p_batt <= 0 }}
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: Battery full, curtail PV export
            action: input_text.set_value
          - data:
              control_mode: Maximum Self Consumption
              export_limit_kw: 0
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: >-
              {{ soc >= soc_full_threshold and p_pv > 0 and p_grid < 0 and
              p_batt <= 0 }}
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: Battery full, export PV to grid
            action: input_text.set_value
          - data:
              control_mode: Maximum Self Consumption
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: >-
              {{ p_pv_curtailment > 0 and p_batt == 0 and p_grid == 0 and
              (states('sensor.amber_effective_general_price') | float) <=
              (states('input_number.emhass_weight_battery_discharge') | float)
              }}
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: >-
                Partial PV curtailment, prevent charging and export, prevent
                discharge
            action: input_text.set_value
          - data:
              control_mode: Maximum Self Consumption
              export_limit_kw: 0
              charge_limit_kw: 0
              discharge_limit_kw: 0
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: "{{ p_pv_curtailment > 0 and p_batt == 0 and p_grid == 0 }}"
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: >-
                Partial PV curtailment, prevent charging and export, permit
                discharge
            action: input_text.set_value
          - data:
              control_mode: Maximum Self Consumption
              charge_limit_kw: 0
              export_limit_kw: 0
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: "{{ p_pv > 0 and p_grid > 0 and p_batt == 0 }}"
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: >-
                Consume from PV, then grid, prevent discharging, permit charge
                then export
            action: input_text.set_value
          - data:
              control_mode: Maximum Self Consumption
              discharge_limit_kw: 0
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: "{{ p_pv_curtailment > 0 and p_grid == 0 and p_batt < 0 }}"
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: Partial PV curtailment, prevent export, limit charge rate
            action: input_text.set_value
          - data:
              control_mode: Maximum Self Consumption
              charge_limit_kw: "{{ (-p_batt / 1000) | round(3) }}"
              export_limit_kw: 0
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: "{{ p_pv_curtailment > 0 and p_grid == 0 }}"
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: Partial PV curtailment, prevent export
            action: input_text.set_value
          - data:
              control_mode: Maximum Self Consumption
              export_limit_kw: 0
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: "{{ p_grid == p_load and p_batt == 0 and p_pv == 0 }}"
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: Consume from grid, battery idle
            action: input_text.set_value
          - data:
              control_mode: Maximum Self Consumption
              discharge_limit_kw: 0
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: "{{ p_batt > 0 and p_grid > 0 }}"
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: Partial self-consume from battery, then grid, permit export
            action: input_text.set_value
          - data:
              control_mode: Maximum Self Consumption
              discharge_limit_kw: "{{ (p_batt / 1000) | round(3) }}"
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: "{{ p_grid == 0 }}"
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: Self-consume from battery
            action: input_text.set_value
          - data:
              control_mode: Maximum Self Consumption
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: >-
              {{ p_batt == 0 and p_pv > 0 and p_grid < 0 and
              (states('sensor.amber_effective_general_price') | float) <=
              (states('input_number.emhass_weight_battery_discharge') | float)}}
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: Export PV to grid, prevent charging, prevent discharge
            action: input_text.set_value
          - data:
              control_mode: Maximum Self Consumption
              charge_limit_kw: 0
              discharge_limit_kw: 0
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: "{{ p_batt == 0 and p_pv > 0 and p_grid < 0 }}"
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: Export PV to grid, prevent charging, allow discharge
            action: input_text.set_value
          - data:
              control_mode: Maximum Self Consumption
              charge_limit_kw: 0
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: "{{ p_batt < 0 and p_grid < 0 }}"
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: Partial charge, then export PV to grid
            action: input_text.set_value
          - data:
              control_mode: Maximum Self Consumption
              charge_limit_kw: "{{ (-p_batt / 1000) | round(3) }}"
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: >-
              {{ soc < (states('input_number.battery_soc_min_export') | float)
              and p_grid < 0 and p_pv > p_load }}
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: Low SOC, export PV to grid, prevent charging, allow discharge
            action: input_text.set_value
          - data:
              control_mode: Maximum Self Consumption
              charge_limit_kw: 0
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: >-
              {{ soc < (states('input_number.battery_soc_min_export') | float)
              }}
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: Low SOC, self-consume from battery
            action: input_text.set_value
          - data:
              control_mode: Maximum Self Consumption
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: >-
              {{ p_hybrid_inverter >= max_inverter_discharge or p_grid <=
              max_grid_export }}
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: Force discharge to grid at full rate
            action: input_text.set_value
          - data:
              control_mode: Command Discharging (PV First)
            action: script.configure_sigen_ems_state
      - conditions:
          - condition: template
            value_template: "{{ p_grid < 0 }}"
        sequence:
          - data_template:
              entity_id: input_text.emhass_battery_action
              value: Force discharge to grid at partial rate
            action: input_text.set_value
          - data:
              control_mode: Command Discharging (PV First)
              export_limit_kw: "{{ (-p_grid / 1000) | round(3) }}"
            action: script.configure_sigen_ems_state
    default:
      - data_template:
          entity_id: input_text.emhass_battery_action
          value: DEFAULT Self-consume from battery
        action: input_text.set_value
      - data:
          control_mode: Maximum Self Consumption
        action: script.configure_sigen_ems_state
trace:
  stored_traces: 10
mode: single

